version: '3'

services:
  itjobsmeter_frontend:
    image: amirtheahmed/itjobsmeter_frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coming-soon.rule=Host(`itjobsmeter.amirtheahmed.dev`, `www.itjobsmeter.amirtheahmed.dev`)"
      - "traefik.http.routers.coming-soon.entrypoints=https"
    environment:
      - NGINX_PORT=80
    networks:
      - proxy

networks:
  proxy:
    external: true